version: '2'
services:
    web:    
        image: nginx:latest
        container_name: nginx
        ports:
            - "8000:80"
            - "3000:443"
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web:/web"
        depends_on:
            - "php"
            - "mariadb"
    php:
        image: php:7.0-fpm
        container_name: php
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - ./web:/web
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mariadb
        restart: always
        depends_on:
            - "mariadb"
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        restart: always
        environment:
            - MYSQL_DATABASE=setserver
            - MYSQL_ROOT_PASSWORD=dev
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=dev
        volumes:
            - ./database/cp:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
    node:
        build: ./app
        container_name: node
        restart: always
        ports:
            - "7000:7000"
        links:
            - "mariadb:mariadb"
        depends_on:
            - "mariadb"