version: '2'
services:
    web:
        image: nginx:latest
        ports:
            - "8000:80"
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./web:/web"
        depends_on:
            - "php"
            - "mariadb"
    php:
        image: php:7-fpm
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - ./web:/web
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        restart: always
        depends_on:
            - "mariadb"
    mariadb:
        image: mariadb:latest
        container_name: MariaDB
        command: mysqld --innodb-buffer-pool-size=20M
        volumes:
            - ./data/db/mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=DB
